version: '3'
services:
  app:
    build: .
    environment:
      - WESIM_DATA_FILE=/data/wesim_data.xlsx
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./datahub:/src/app
      - ./log:/src/log
      - ../1_Wesim_GB_hourly_data.xlsx:/data/wesim_data.xlsx
